### ISSUE TITLE
Ajout d'un élément "html" aux dynamics forms

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#1043]
Afin de permettre d'insérer du HTML au sein des formulaires dynamiques (composant GeoNature), un nouveau type de widget est défini ci-dessous.

Les paramètres de  ce nouveau type de widget seront les suivant:
 - `type_widget` [= "html"]: indique un widget de type HTML dont le contenu sera inséré dans une balise DIV.
 - `attribut_name`: ce nom utilisé pour définir la partie fixe l'attribut "id" de la balise DIV.
 - `class`: classes CSS ajoutées à l'attribut "class" de la balise DIV.
 - `html`: contenu HTML à insérer dans la balise DIV. 

Exemple de paramétrage pour le formulaire d'inscription GeoNature:
```toml
    [[ACCOUNT_MANAGEMENT.ACCOUNT_FORM]]
        type_widget = "html"
        attribut_name = "conditions"
        class = "alert alert-primary"
        html = """
            <p>Merci pour votre demande d’inscription. Après 
            <strong>validation de l’administrateur</strong>, vous 
            pourrez accéder aux observations publiques avec leur 
            précision de géolocalisation maximale.</p>"""
```
