### ISSUE TITLE
Formulaire de demande de permissions

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#1062]
Voir le ticket #770  pour le contexte générale de ce ticket.
Pour rappel, le cahier des charges / suivi du développement est [disponible sur ce lien](https://wiki-sinp.cbn-alpin.fr/fonctionnalites/geonature/developpements-prioritaires#formulaire_de_demande_de_permissions_d_acces).

En bref:
- l'ensemble de cette fonctionnalité est absente de l'installation de base. Elle est activable via le fichier de config de GeoNature.
- ajout d'une entrée au menu "Mon compte/Profil" présent dans l'entête de l'interface de GeoNature. 
- développement d'un composant `access-request` dans le nouveau module `permission` permettant de fournir un formulaire de demande de permissions d'accès
- le formulaire comprend une partir fixe (champs "Zones géographiques", "Groupes taxonomiques", "Observations sensibles" et "Accès jusqu'au") et une partie configurable à l'aide d'un formulaire dynamique fonctionnant sur le même principe que celui du formulaire d'inscription.

Ajout des paramètres de configuration suivant:
```toml
[PERMISSION_MANAGEMENT]
    # Activer (=true) l'affichage du lien vers le formulaire de demande 
    # de permissions. Par défaut : désactivé (=false).
    ENABLE_ACCESS_REQUEST = false
    # Lien vers les règles d'accès aux observations sensibles propres à
    # cette instance de GeoNature
    SENSITIVE_DATA_ACCESS_RULES_LINK = "https://inpn.mnhn.fr/docs/demandes_sinp/Licence_ferme_SINP.pdf"
    # Liste d'id (table `ref_geo.bib_areas_type`, champ `id_type`) des 
    # types de zones géographique sélectionnables dans le filtre par 
    # zones géographiques du formulaire de demande d'accès.
    # Par défaut : Communes (=25) et Départements (=26).
    AREA_TYPES = [25, 26]
    # Durée par défaut en jour pendant laquelle l'accès est autorisé.
    # Le champ "Accès jusqu'au" sera automatiquement rempli avec une date
    # correspondant à nombre de jour dans le futur.
    # Par défaut, ce champ n'apparait pas et l'accès est permanent.
    DEFAULT_ACCESS_DURATION = 90
    # Durée maximum en jour pendant laquelle l'accès peut être autorisé.
    # La date saisie dans le champ "Accès jusqu'au"devra se situé entre 
    # le jour courrant et ce nombre de jours dans le futur.
    # Par défaut, la demande d'accès maximum est de 1 ans.
    MAX_ACCESS_DURATION = 365
    # Titre de la section personnalisable du formulaire de demande d'accès
    REQUEST_FORM_TITLE = "Motivations de la demande"
    # Définition de la section personnalisable du formulaire de demande 
    # de permission d'accès.
    [[PERMISSION_MANAGEMENT.REQUEST_FORM]]
        type_widget = "html"
        attribut_name = "motivation-intro"
        html = """
            <small class="form-text">
                Veuillez décrire ci-dessous les motivations à l'origine 
                de votre demande.
            </small>"""
   [[PERMISSION_MANAGEMENT.REQUEST_FORM]]
        type_widget = "textarea"
        attribut_label = "Description"
        attribut_name = "project-description"
        required = false
        help = """Préciser le calendrier, la finalité, l'objet de l’étude 
            scientifique et le cadre réglementaire dans lequel s’inscrit 
            la demande."""
```
