### ISSUE TITLE
[Synthese] Désactivation des clusters Leaflet

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#3510]
Proposition d'ajout d'un paramètre de configuration (`LEALET_CLUSTER_DISABLE_ZOOM`) permettant de désactiver les clusters Leaflet, pour le module Synthese, à partir d'un certain niveau de zoom.

```toml
[SYNTHESE]
    # Disable Leaflet clusters on the map at this zoom level
    # ⚠ WARNING: check if all search results are working !
    LEALET_CLUSTER_DISABLE_ZOOM = 16
```

La désactivation des clusters pouvant entraîner un blocage de l'application GeoNature côté navigateur web s'il y a encore trop de données afficher à l'écran, le paramètre est désactivé par défaut.
